# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: mnist.yaml
  - model: mnist.yaml
  - callbacks: default.yaml
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default.yaml

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# compile model for faster training with pytorch 2.0
compile: False

# simply provide checkpoint path to resume training
ckpt_path: null

# ckpt_path: "checkpoints/ucfcrime/last.ckpt" #for original model
# ckpt_path: "checkpoints/ucfcrime/epoch_049-v3.ckpt" #for 0.4 
# ckpt_path: "checkpoints/ucfcrime/epoch_051.ckpt" #for 0.5
# ckpt_path: "checkpoints/ucfcrime/epoch_051-v2.ckpt" #for 0.8
# ckpt_path: "checkpoints/ucfcrime/epoch_051-v1.ckpt" #for 0.3

# ckpt_path: "checkpoints/shanghaitech/last.ckpt" #for original model
# ckpt_path: "checkpoints/shanghaitech/epoch_101.ckpt" #for 0.5
# ckpt_path: "checkpoints/shanghaitech/epoch_100.ckpt" #for 0.4
# ckpt_path: "checkpoints/shanghaitech/epoch_101-v1.ckpt" #for 0.3
# ckpt_path: "checkpoints/shanghaitech/epoch_099-v1.ckpt" #for 0.6
# ckpt_path: "checkpoints/shanghaitech/epoch_101-v2.ckpt" #for 0.8

# ckpt_path: "checkpoints/xdviolence/last.ckpt" #for original model
# ckpt_path: "checkpoints/xdviolence/epoch_051.ckpt" #for 0.5
# ckpt_path: "checkpoints/xdviolence/epoch_051-v1.ckpt" #for 0.3
# ckpt_path: "checkpoints/xdviolence/epoch_051-v2.ckpt" #for 0.8

# seed for random number generators in pytorch, numpy and python.random
seed: null
